packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@prisma/engines@7.8.0": true
  "esbuild@0.28.1": true
  "msgpackr-extract@3.0.4": true
  "prisma@7.8.0": true
  "sharp@0.34.5": true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.0'
  - '@turbo/darwin-arm64@2.10.0'
  - '@turbo/linux-64@2.10.0'
  - '@turbo/linux-arm64@2.10.0'
  - '@turbo/windows-64@2.10.0'
  - '@turbo/windows-arm64@2.10.0'
  - '@types/node@26.0.1'
  - turbo@2.10.0
